services:
  app:
    build: .
    ports:
      - "5010:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./app:/app/app

  redis:
    image: "redis:alpine"
